services:
  web:
    image: nginx
    networks:
      - frontend
  api:
    build: .
    networks:
      - frontend
      - backend
  db:
    image: postgres:13
    networks:
      - backend
neworks:
  frondend:
  backend:
    
    


  
    