services:
  db:
   image: postgres:13
   volumes:
     - db_data:/var/lib/postgresql/data
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html:ro
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
  volumes:
    db_data:
      
    