services:
  web:
    image: nginx
    depends_on:
      - db
      - api
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
  db: 
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    


  
    